In [2]:
import sys
import numpy as np
import matplotlib.pyplot as plt
from Bio.Seq import Seq
#from matplotlib.colors import Normalize
import matplotlib.cbook as cbook
import numpy.ma as ma
import pandas as pd
#import seaborn as sns
import seaborn as sns

import pandas as pd
sys.path.append( '/home/strauch/scripts/gabes' )
import get_seq

#from scipy import stats
import os
import glob
#import re
#import math

In [3]:
def fix_file_read_df(myfile):
    
    tmp = open('temp.csv','w')
    f = open(myfile,'r').readlines()
    header = f[1].split()
    print len(header)
    for idx in range(1,len(f)-1):
        line = f[idx]
        its = line.split()
        row = []
        if len(its) == len(header):
            for i in its:
                i = i.strip()
                row.append(str(i))
            #print row
            print >> tmp , ','.join(row)
    #print i
    #print line
    tmp.close()
    df = pd.read_csv('temp.csv',sep=',',header=(0))#,index_col = 'description')
    return df

In [4]:
#df = fix_file_read_df('score_enhanced.sc')
df = pd.read_csv('score_enhanced.sc',sep='\s',header=(1))
df.head()

/home/strauch/venv/lib/python2.7/site-packages/ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.

,SCORE:,total_score,AlaCount,buns3,cavity,contact,contact_per_res,degree2,degreeB,dslf_fa13,...,chymo_cut_sites,chymo_with_LM_cut_sites,nearest_chymo_cut_to_Nterm,nearest_chymo_cut_to_Cterm,nearest_tryp_cut_to_Nterm,nearest_tryp_cut_to_Cterm,nearest_tryp_cut_to_term,nearest_chymo_cut_to_term,sequence,description
0,SCORE:,-189.117,5.0,2.0,0.000,150.0,2.586,10.621,10.621,0.0,...,2,3.5,9,38,7,6,6,9,DPTEDARKWAKDVGSPVAEKFIKKLESEVSPQEAAKVVKELKKQNK...,ems_4hC_1313_0001
1,SCORE:,-189.117,5.0,2.0,0.000,150.0,2.586,10.621,10.621,0.0,...,2,3.5,9,38,7,6,6,9,DPTEDARKWAKDVGSPVAEKFIKKLESEVSPQEAAKVVKELKKQNK...,ems_4hC_1313_0001
2,SCORE:,-208.222,6.0,1.0,0.000,157.0,2.617,10.767,10.767,0.0,...,2,4.5,2,23,8,6,6,2,DYQDEAEKLAKKVARDPNLQEKASKLVRSNPEVAKKLFKLVRSAQT...,ems_4hC_2570_0001
3,SCORE:,-196.829,6.0,1.0,20.559,124.0,2.102,10.898,10.898,0.0,...,0,3.5,59,59,4,7,4,59,DESKEVTELLKKVVDLANNPDAKENAEKLVRDDTDKAKDLARKLQN...,ems_4hC_1245_0001
4,SCORE:,-196.829,6.0,1.0,20.559,124.0,2.102,10.898,10.898,0.0,...,0,3.5,59,59,4,7,4,59,DESKEVTELLKKVVDLANNPDAKENAEKLVRDDTDKAKDLARKLQN...,ems_4hC_1245_0001

In [5]:
list(df)

['SCORE:',
 'total_score',
 'AlaCount',
 'buns3',
 'cavity',
 'contact',
 'contact_per_res',
 'degree2',
 'degreeB',
 'dslf_fa13',
 'exposed_hydrophobics',
 'fa_atr',
 'fa_atr_per_res',
 'fa_dun',
 'fa_elec',
 'fa_intra_rep',
 'fa_intra_sol_xover4',
 'fa_rep',
 'fa_sol',
 'faulty_fragments',
 'hbond_bb_sc',
 'hbond_lr_bb',
 'hbond_sc',
 'hbond_sfn',
 'hbond_sr_bb',
 'holes',
 'hx_sc',
 'lk_ball_wtd',
 'mean_hbond',
 'np_count',
 'np_res',
 'omega',
 'p_aa_pp',
 'pack',
 'percent_core_SCN',
 'pp_mm',
 'pro_close',
 'rama_prepro',
 'ref',
 'score_per_res',
 'ss_has_core',
 'total_score_cen',
 'unsat_hbond',
 'yhh_planarity',
 'n_res',
 'dssp',
 'nres_helix',
 'nres_sheet',
 'nres_loop',
 'frac_helix',
 'frac_sheet',
 'frac_loop',
 'hbond_sr_bb_per_helix',
 'hbond_lr_bb_per_sheet',
 'T1_netq',
 'Tminus1_netq',
 'Tend_netq',
 'T1_absq',
 'Tminus1_absq',
 'Tend_absq',
 'abego_res_profile',
 'abego_res_profile_penalty',
 'largest_hphob_cluster',
 'n_hphob_clusters',
 'hphob_sc_contacts',
 'hphob_sc_degree',
 'buried_np_AFILMVWY',
 'exposed_np_AFILMVWY',
 'buried_np_AFILMVWY_per_res',
 'netcharge',
 'n_charged',
 'n_hydrophobic',
 'n_hydrophobic_noA',
 'hydrophobicity',
 'contig_not_hp_max',
 'contig_not_hp_internal_max',
 'contig_not_hp_avg',
 'contig_not_hp_avg_norm',
 'fa_rep_per_res',
 'net_atr_per_res',
 'net_sol_per_res',
 'net_atr_net_sol_per_res',
 'tryp_cut_sites',
 'chymo_cut_sites',
 'chymo_with_LM_cut_sites',
 'nearest_chymo_cut_to_Nterm',
 'nearest_chymo_cut_to_Cterm',
 'nearest_tryp_cut_to_Nterm',
 'nearest_tryp_cut_to_Cterm',
 'nearest_tryp_cut_to_term',
 'nearest_chymo_cut_to_term',
 'sequence',
 'description']

In [6]:
col = ['sequence','worstfrag','worst6frags','sum_best_frags','avg_all_frags']
f = pd.read_csv('allfrags',sep='\s' ,header=None,usecols=[1,2,9,11,12],names=col)                               
f['n'] = f['sequence'].apply(lambda x: (len(x)- 8) )
f['avg_best_frag'] = f['sum_best_frags']/ f['n'] 
f.head()

/home/strauch/venv/lib/python2.7/site-packages/ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.

,sequence,worstfrag,worst6frags,sum_best_frags,avg_all_frags,n,avg_best_frag
0,NEEVAKKANEAVKEGDVDKVVDLLRKVNNDELVKWVVKLAREIDKD...,1.6441,6.3877,17.6855,1.064981,52,0.340106
1,DIYEKLAKIASELVGDPSIEEILRKLVDGNPEVSKLLKSVLNTTDE...,0.7921,4.0570,15.0132,1.316052,49,0.306392
2,DELTKILEHVASIADPNLTKTVHELYKKDPDTASSIAKELQKILES...,0.8351,3.8592,14.0666,1.114657,56,0.251189
3,DQQEEAQKLAEKVKQDLRDPAADQFAKTVKNLSKDEARTLWKQLHD...,0.9883,4.9813,16.5381,1.073179,54,0.306261
4,DEQDVERTVTKKARDNNTEKDVKSAKKVDPETFTKAVQSAYRTGDD...,1.6036,6.5301,18.5746,1.307140,53,0.350464

In [7]:
out = ['sequence',
     'worstfrag',
     'worst6frags',
     'sum_best_frags',
     'avg_all_frags',
     'avg_best_frag']

In [8]:
angles = pd.read_csv('score_bb_angles.csv')
angles.head()

,description,omega_min,omega_avg,omega_max,rama_max,rama_avg
0,ems_coilC_130_0001,172.073960,176.941130,179.867127,1.10577,-0.114917
1,ems_ferrC_1910_0002_0001,166.880094,177.073897,179.903558,0.38230,-0.157089
2,ems_ferrM_4204_0001,168.099900,176.598902,179.989282,0.26783,-0.143793
3,ems_4hC_2190_0001,169.515363,176.814544,179.995306,0.86680,-0.127428
4,ems_4hM_924_0001,168.658045,176.475620,179.959962,0.48511,-0.151495

In [9]:
print len(angles.index)

21990

In [10]:
combine = pd.merge(left=df, right=f[out], on='sequence',how='inner')
combine.head()

,SCORE:,total_score,AlaCount,buns3,cavity,contact,contact_per_res,degree2,degreeB,dslf_fa13,...,nearest_tryp_cut_to_Cterm,nearest_tryp_cut_to_term,nearest_chymo_cut_to_term,sequence,description,worstfrag,worst6frags,sum_best_frags,avg_all_frags,avg_best_frag
0,SCORE:,-189.117,5.0,2.0,0.00,150.0,2.586,10.621,10.621,0.0,...,6,6,9,DPTEDARKWAKDVGSPVAEKFIKKLESEVSPQEAAKVVKELKKQNK...,ems_4hC_1313_0001,0.881,4.821,16.5712,1.293802,0.331424
1,SCORE:,-189.117,5.0,2.0,0.00,150.0,2.586,10.621,10.621,0.0,...,6,6,9,DPTEDARKWAKDVGSPVAEKFIKKLESEVSPQEAAKVVKELKKQNK...,ems_4hC_1313_0001,0.881,4.821,16.5712,1.293802,0.331424
2,SCORE:,-189.117,5.0,2.0,0.00,150.0,2.586,10.621,10.621,0.0,...,6,6,9,DPTEDARKWAKDVGSPVAEKFIKKLESEVSPQEAAKVVKELKKQNK...,ems_4hC_1313_0001,0.881,4.821,16.5712,1.293802,0.331424
3,SCORE:,-189.117,5.0,2.0,0.00,150.0,2.586,10.621,10.621,0.0,...,6,6,9,DPTEDARKWAKDVGSPVAEKFIKKLESEVSPQEAAKVVKELKKQNK...,ems_4hC_1313_0001,0.881,4.821,16.5712,1.293802,0.331424
4,SCORE:,-189.117,5.0,2.0,15.57,150.0,2.586,10.621,10.621,0.0,...,6,6,9,DPTEDARKWAKDVGSPVAEKFIKKLESEVSPQEAAKVVKELKKQNK...,ems_4hM_1670_0001,0.881,4.821,16.5712,1.293802,0.331424

In [11]:
len(combine.index)

36452

In [12]:
print len(f.index)

21990

In [23]:
c = combine.drop_duplicates('description')
print len(c.index)

21816

In [29]:
merged2 = pd.merge(left=c, right=angles, on='description', how='outer')#suffixes=['_chymo', '_trp'], how='inner')
print len(merged2.index)
merged2.head()

29041

,SCORE:,total_score,AlaCount,buns3,cavity,contact,contact_per_res,degree2,degreeB,dslf_fa13,...,worstfrag,worst6frags,sum_best_frags,avg_all_frags,avg_best_frag,omega_min,omega_avg,omega_max,rama_max,rama_avg
0,SCORE:,-189.117,5.0,2.0,0.000,150.0,2.586,10.621,10.621,0.0,...,0.8810,4.8210,16.5712,1.293802,0.331424,167.633840,177.047503,179.892884,0.21616,-0.183987
1,SCORE:,-189.117,5.0,2.0,15.570,150.0,2.586,10.621,10.621,0.0,...,0.8810,4.8210,16.5712,1.293802,0.331424,167.633840,177.047503,179.892884,0.21616,-0.183987
2,SCORE:,-208.222,6.0,1.0,0.000,157.0,2.617,10.767,10.767,0.0,...,0.8076,4.3238,14.4744,1.152468,0.278354,170.118268,177.228779,179.973489,0.18121,-0.146522
3,SCORE:,-196.829,6.0,1.0,20.559,124.0,2.102,10.898,10.898,0.0,...,1.5563,7.4559,21.4888,1.451002,0.421349,170.329698,176.776528,179.945717,0.40698,-0.167695
4,SCORE:,-196.829,6.0,1.0,0.000,124.0,2.102,10.898,10.898,0.0,...,1.5563,7.4559,21.4888,1.451002,0.421349,170.329698,176.776528,179.945717,0.40698,-0.167695

In [31]:
m1 = merged2.drop_duplicates('description')
print len(m1.index)

29041

In [32]:
#m= merged2.set_index('description')
m= m1.set_index('description')
m.to_csv('c.csv')
m.head()

,SCORE:,total_score,AlaCount,buns3,cavity,contact,contact_per_res,degree2,degreeB,dslf_fa13,...,worstfrag,worst6frags,sum_best_frags,avg_all_frags,avg_best_frag,omega_min,omega_avg,omega_max,rama_max,rama_avg
description,,,,,,,,,,,,,,,,,,,,,
ems_4hC_1313_0001,SCORE:,-189.117,5.0,2.0,0.000,150.0,2.586,10.621,10.621,0.0,...,0.8810,4.8210,16.5712,1.293802,0.331424,167.633840,177.047503,179.892884,0.21616,-0.183987
ems_4hM_1670_0001,SCORE:,-189.117,5.0,2.0,15.570,150.0,2.586,10.621,10.621,0.0,...,0.8810,4.8210,16.5712,1.293802,0.331424,167.633840,177.047503,179.892884,0.21616,-0.183987
ems_4hC_2570_0001,SCORE:,-208.222,6.0,1.0,0.000,157.0,2.617,10.767,10.767,0.0,...,0.8076,4.3238,14.4744,1.152468,0.278354,170.118268,177.228779,179.973489,0.18121,-0.146522
ems_4hC_1245_0001,SCORE:,-196.829,6.0,1.0,20.559,124.0,2.102,10.898,10.898,0.0,...,1.5563,7.4559,21.4888,1.451002,0.421349,170.329698,176.776528,179.945717,0.40698,-0.167695
ems_4hM_1873_0001,SCORE:,-196.829,6.0,1.0,0.000,124.0,2.102,10.898,10.898,0.0,...,1.5563,7.4559,21.4888,1.451002,0.421349,170.329698,176.776528,179.945717,0.40698,-0.167695

In [2]:
files = []
for f in os.listdir('./'):
    #print f
    if 'temp.csv' in f:
        print "not temp"
    else:
        if '.csv' in f:
            files.append(f)
print files

for i in range(1,len(files)):
    cfile = files[i]
    df1 = pd.read_csv(cfile,sep=',',header=(0))
    df = df.append(df1)

[]

In [65]:
directories = []
for i in files:
    n= i.strip('.csv')
    #print n
    n = 'selected_' + n
    print n
    directories.append(n)

selected_d2m_bunsless3
selected_d2m1

In [66]:
def get_frag_file(fragfile):#directories[0]
    
    col = ['sequence','worstfrag','worst6frags','sum_best_frags','avg_all_frags']
    f = pd.read_csv(fragfile +'/' + 'score.sc.frag_quals',sep='\s' ,header=None,usecols=[1,2,9,11,12],names=col)                               
    f['n'] = f['sequence'].apply(lambda x: (len(x)- 8) )
    f['avg_best_frag'] = f['sum_best_frags']/ f['n'] 

    #f.head()
    return f

In [84]:
out = ['sequence',
     'worstfrag',
     'worst6frags',
     'sum_best_frags',
     'avg_all_frags',
     'avg_best_frag']

    
dfs = {}
for idx in range(len(files)):
    print files[idx],directories[idx]
    df = pd.read_csv(files[idx],sep=',',header=(0))
    print len(df.index)
    df.head()
    
    frags = get_frag_file(directories[idx])
    score_dict = pd.merge(left=df, right=frags[out], on='sequence',how='left')
    score_dict.head()

    dfs[idx] = score_dict

alldata = pd.concat(dfs)
alldata.head()
print len(alldata)

d2m_bunsless3.csv selected_d2m_bunsless3
3535
d2m1.csv selected_d2m1
2318
5853

/home/strauch/venv/lib/python2.7/site-packages/ipykernel_launcher.py:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  after removing the cwd from sys.path.

In [85]:
myfile = open('renamed.list','r').readlines()
d = {}
des = []
names = []
for line in myfile:
    its = line.split()
    name = its[0].split('/')[-1]
    #print name.strip('.pdb'), 
    #print its[1]
    d[its[1]] = name.strip('.pdb')
    des.append(name.strip('.pdb'))
    names.append(its[1])

In [86]:
#columns = ['name','description']
#dfnames = pd.DataFrame.from_dict(d.items(),columns)
#dfnames.columns['i','name','description']
dfnames = pd.DataFrame({'name': names,'description': des})
dfnames.head()

               description       name
0  4h_b0168_0185_0003_0001  ems_4hM_1
1  4h_b0056_0017_0004_0001  ems_4hM_2
2  4h_b0168_0065_0003_0001  ems_4hM_3
3  4h_b0131_0155_0003_0001  ems_4hM_4
4  4h_b0071_0026_0001_0001  ems_4hM_5

In [103]:
angles = pd.read_csv('score_bb_angles.csv')
angles.head()

,description,omega_min,omega_avg,omega_max,rama_max,rama_avg
0,4h_b0080_0304_0001_0001,169.142958,176.807826,179.735816,0.28874,-0.113488
1,4h_b0035_0376_0002_0001,168.638165,177.231984,179.984468,0.34205,-0.172033
2,4h_b0193_0213_0002_0001,172.624448,177.603522,179.954057,0.66725,-0.158565
3,4h_b0080_0012_0001_0001,167.482396,177.123539,179.973881,0.36155,-0.156984
4,4h_b0035_0363_0001_0001,169.768920,177.176615,179.950707,0.32910,-0.203019

In [104]:
merged = pd.merge(left=dfnames, right=alldata, on='description', how='inner')#suffixes=['_chymo', '_trp'], how='inner')

In [105]:
merged.head()

,description,name,SCORE:,total_score,AlaCount,buns3,cavity,contact,contact_per_res,degree2,...,nearest_tryp_cut_to_Nterm,nearest_tryp_cut_to_Cterm,nearest_tryp_cut_to_term,nearest_chymo_cut_to_term,sequence,worstfrag,worst6frags,sum_best_frags,avg_all_frags,avg_best_frag
0,4h_b0168_0185_0003_0001,ems_4hM_1,SCORE:,-191.604,4.0,2.0,0.000,128.0,2.207,10.345,...,2,2,2,26,SKETVIKRIRKAVEGSPVQEEVERQYKKNELKKIVDKAVKNNTSEE...,2.9561,12.3945,25.0637,1.427188,0.501274
1,4h_b0056_0017_0004_0001,ems_4hM_2,SCORE:,-211.832,6.0,1.0,10.279,169.0,2.683,10.556,...,7,3,3,4,DPDEVAKTVQKAAKNNDPTKVYQALKEASKTPNSKDKVQKIIKSQD...,1.2154,5.3632,14.0262,1.231495,0.255022
2,4h_b0168_0065_0003_0001,ems_4hM_3,SCORE:,-225.443,6.0,2.0,36.128,185.0,2.937,10.873,...,3,5,3,13,DVKTELSQLAKVLGDPVVKEAATQASKVVDNNDPETAKKVFRTVIS...,1.5120,8.1221,22.2807,1.242657,0.405104
3,4h_b0131_0155_0003_0001,ems_4hM_4,SCORE:,-222.032,6.0,2.0,12.742,165.0,2.538,10.877,...,6,3,3,17,DQEELKEELTKILSNAYNNPELAKRASKIVKSDPQVSEEAKKLVEK...,0.8548,3.6551,14.8981,1.050131,0.261370
4,4h_b0071_0026_0001_0001,ems_4hM_5,SCORE:,-210.114,5.0,2.0,12.742,176.0,2.794,11.127,...,6,3,3,20,DEELLKKASEILKNGNAEKFVKIFQTASKRLGDEDTSKTLKKEASD...,0.8293,3.9393,14.2612,1.193704,0.259295

In [108]:
merged.tail()

,description,name,SCORE:,total_score,AlaCount,buns3,cavity,contact,contact_per_res,degree2,...,nearest_tryp_cut_to_Nterm,nearest_tryp_cut_to_Cterm,nearest_tryp_cut_to_term,nearest_chymo_cut_to_term,sequence,worstfrag,worst6frags,sum_best_frags,avg_all_frags,avg_best_frag
5718,4h_b0069_0122_0001_0001,ems_4hM_5538,SCORE:,-225.042,4.0,0.0,0.000,182.0,3.033,10.833,...,4,6,4,3,PLWKEVTELAKKADPDVSKVEELLKKFLKSLDPDQLRKIKTKLERD...,1.3855,6.3506,18.3619,1.190721,0.353113
5719,4h_b0026_0251_0001_0001,ems_4hM_5539,SCORE:,-204.938,4.0,2.0,61.613,163.0,2.810,10.552,...,5,2,2,1,DEDEKIEKELSERVDEELRKAVQKALKDPHWRKLLKKALSKGDETE...,2.6151,12.2493,23.8995,1.132528,0.477990
5720,4h_b0042_0396_0001_0001,ems_4hM_5540,SCORE:,-216.290,4.0,2.0,22.418,160.0,2.500,10.375,...,8,1,1,5,DIVEEAEKILNQVDDSAEDVVKVFIREANDPRKREEAQKKVDTLRK...,1.7469,7.0244,22.7912,1.187014,0.406986
5721,4h_b0151_0062_0001_0001,ems_4hM_5541,SCORE:,-213.421,5.0,2.0,31.529,198.0,3.246,10.541,...,7,4,4,3,DVEEIIRRAYKLISDPRNQEEAQKLVEKVDKDPTARKKLDKLSKDD...,0.7827,4.1551,16.5033,1.314192,0.311383
5722,4h_b0013_0216_0002_0001,ems_4hM_5542,SCORE:,-230.392,6.0,1.0,23.022,188.0,2.938,10.781,...,3,7,3,10,DAKEKLNKAVKLVRSRTNEEEAQKIVKELVSDHLREKADEWVKEAS...,2.7850,12.8335,30.9325,1.393651,0.552366

In [106]:
merged2 = pd.merge(left=merged, right=angles, on='description', how='inner')#suffixes=['_chymo', '_trp'], how='inner')

In [107]:
print len(merged2.index)
merged2.head()
new = merged2.set_index('name')
new.head()

6071

,description,SCORE:,total_score,AlaCount,buns3,cavity,contact,contact_per_res,degree2,degreeB,...,worstfrag,worst6frags,sum_best_frags,avg_all_frags,avg_best_frag,omega_min,omega_avg,omega_max,rama_max,rama_avg
name,,,,,,,,,,,,,,,,,,,,,
ems_4hM_1,4h_b0168_0185_0003_0001,SCORE:,-191.604,4.0,2.0,0.000,128.0,2.207,10.345,10.345,...,2.9561,12.3945,25.0637,1.427188,0.501274,172.524201,177.743038,179.983966,0.29968,-0.219913
ems_4hM_2,4h_b0056_0017_0004_0001,SCORE:,-211.832,6.0,1.0,10.279,169.0,2.683,10.556,10.556,...,1.2154,5.3632,14.0262,1.231495,0.255022,171.666023,177.391864,179.952414,0.82347,-0.132073
ems_4hM_3,4h_b0168_0065_0003_0001,SCORE:,-225.443,6.0,2.0,36.128,185.0,2.937,10.873,10.873,...,1.5120,8.1221,22.2807,1.242657,0.405104,166.675505,177.409366,179.961116,0.51516,-0.104705
ems_4hM_4,4h_b0131_0155_0003_0001,SCORE:,-222.032,6.0,2.0,12.742,165.0,2.538,10.877,10.877,...,0.8548,3.6551,14.8981,1.050131,0.261370,170.540740,177.119763,179.853052,0.38835,-0.161349
ems_4hM_5,4h_b0071_0026_0001_0001,SCORE:,-210.114,5.0,2.0,12.742,176.0,2.794,11.127,11.127,...,0.8293,3.9393,14.2612,1.193704,0.259295,171.624094,177.561165,179.963058,0.12714,-0.216091

In [109]:
cols = list(new)
print len(cols)
cut = []
for i in cols:
    if 'SCORE' in i:
        continue
    if '0' in i:
        continue
    #if 'description' in i:
    #    continue
    else:
        cut.append(i)
print cut

103
['description', 'total_score', 'AlaCount', 'buns3', 'cavity', 'contact', 'contact_per_res', 'degree2', 'degreeB', 'dslf_fa13', 'exposed_hydrophobics', 'fa_atr', 'fa_atr_per_res', 'fa_dun', 'fa_elec', 'fa_intra_rep', 'fa_intra_sol_xover4', 'fa_rep', 'fa_sol', 'faulty_fragments', 'hbond_bb_sc', 'hbond_lr_bb', 'hbond_sc', 'hbond_sfn', 'hbond_sr_bb', 'holes', 'hx_sc', 'lk_ball_wtd', 'mean_hbond', 'np_count', 'np_res', 'omega', 'p_aa_pp', 'pack', 'percent_core_SCN', 'pp_mm', 'pro_close', 'rama_prepro', 'ref', 'score_per_res', 'ss_has_core', 'total_score_cen', 'unsat_hbond', 'yhh_planarity', 'n_res', 'dssp', 'nres_helix', 'nres_sheet', 'nres_loop', 'frac_helix', 'frac_sheet', 'frac_loop', 'hbond_sr_bb_per_helix', 'hbond_lr_bb_per_sheet', 'T1_netq', 'Tminus1_netq', 'Tend_netq', 'T1_absq', 'Tminus1_absq', 'Tend_absq', 'abego_res_profile', 'abego_res_profile_penalty', 'largest_hphob_cluster', 'n_hphob_clusters', 'hphob_sc_contacts', 'hphob_sc_degree', 'buried_np_AFILMVWY', 'exposed_np_AFILMVWY', 'buried_np_AFILMVWY_per_res', 'netcharge', 'n_charged', 'n_hydrophobic', 'n_hydrophobic_noA', 'hydrophobicity', 'contig_not_hp_max', 'contig_not_hp_internal_max', 'contig_not_hp_avg', 'contig_not_hp_avg_norm', 'fa_rep_per_res', 'net_atr_per_res', 'net_sol_per_res', 'net_atr_net_sol_per_res', 'tryp_cut_sites', 'chymo_cut_sites', 'chymo_with_LM_cut_sites', 'nearest_chymo_cut_to_Nterm', 'nearest_chymo_cut_to_Cterm', 'nearest_tryp_cut_to_Nterm', 'nearest_tryp_cut_to_Cterm', 'nearest_tryp_cut_to_term', 'nearest_chymo_cut_to_term', 'sequence', 'worstfrag', 'worst6frags', 'sum_best_frags', 'avg_all_frags', 'avg_best_frag', 'omega_min', 'omega_avg', 'omega_max', 'rama_max', 'rama_avg']

In [110]:
new[cut].to_csv('scores_renamed.sc')